// Universal company search over the bundled SEC index (public/sec-companies.json,
// generated by backend/build_sec_index.py). Loaded once, searched client-side —
// zero Supabase reads, instant results across all ~10k US public companies.

export type SecCompany = { cik: string; ticker: string; name: string };

let cache: SecCompany[] | null = null;
let inflight: Promise<SecCompany[]> | null = null;

/** Load and cache the bundled index. Returns [] if the file is missing. */
export async function loadSecIndex(): Promise<SecCompany[]> {
  if (cache) return cache;
  if (!inflight) {
    inflight = fetch("/sec-companies.json")
      .then((r) => (r.ok ? r.json() : []))
      .then((d: SecCompany[]) => { cache = Array.isArray(d) ? d : []; return cache; })
      .catch(() => { cache = []; return cache; });
  }
  return inflight;
}

// Strip punctuation + common corporate suffixes so "BlackRock, Inc." ≈ "blackrock"
// and "Apple Inc." ≈ "apple". Lets us recognise when a query names the company
// itself rather than a same-prefixed fund/subsidiary.
const _SUFFIX = /\b(inc|incorporated|corp|corporation|co|company|companies|ltd|limited|plc|lp|llc|holdings?|group|trust|fund|the|sa|nv|ag)\b/g;
function normalizeName(s: string): string {
  return s.toLowerCase().replace(/[.,&/]/g, " ").replace(_SUFFIX, " ").replace(/\s+/g, " ").trim();
}

/**
 * Rank matches so typing feels like a clean prefix filter and the *actual* company
 * surfaces first, not a same-named fund:
 *   1. exact ticker            (type "BLK"       → BlackRock, Inc.)
 *   2. company-name match      (type "blackrock" → BlackRock, Inc. — beats the 38 BlackRock funds)
 *   3. ticker starts-with      (type "A"         → A, AA, AAL, AAPL … alphabetical)
 *   4. name starts-with        (type "app"       → Apple, Applied Materials …)
 *   5. name contains           (type "rock"      → BlackRock … — NAME substrings only)
 * Tickers match by exact/prefix ONLY — a query is never matched mid-ticker, so
 * "BLK" does not pull in "SBLK" (Star Bulk). Ticker buckets sort by ticker, name
 * buckets by name. Scans the whole ~10k index, so nothing is missed.
 */
export function searchSec(index: SecCompany[], query: string, limit = 50): SecCompany[] {
  const n = query.trim().toLowerCase();
  if (!n) return [];
  const nn = normalizeName(n);   // "" for pure-suffix queries like "co" → skip the name-exact tier
  const tickerExact: SecCompany[] = [];
  const nameExact: SecCompany[] = [];
  const tickerPrefix: SecCompany[] = [];
  const namePrefix: SecCompany[] = [];
  const nameContains: SecCompany[] = [];
  for (const c of index) {
    const tk = (c.ticker ?? "").toLowerCase();
    const nm = (c.name ?? "").toLowerCase();
    if (tk === n) tickerExact.push(c);
    else if (nn && normalizeName(nm) === nn) nameExact.push(c);
    else if (tk.startsWith(n)) tickerPrefix.push(c);
    else if (nm.startsWith(n)) namePrefix.push(c);
    else if (nm.includes(n)) nameContains.push(c);   // name substrings only — never mid-ticker
  }
  const byTicker = (a: SecCompany, b: SecCompany) => a.ticker.localeCompare(b.ticker);
  const byName = (a: SecCompany, b: SecCompany) => a.name.localeCompare(b.name);
  nameExact.sort(byTicker);
  tickerPrefix.sort(byTicker);
  namePrefix.sort(byName);
  nameContains.sort(byName);
  return [...tickerExact, ...nameExact, ...tickerPrefix, ...namePrefix, ...nameContains].slice(0, limit);
}
