// Central definitions for the financial / SEC terms used across the UI.
// Single source of truth: KPI tiles, chart info icons, and inline <Term> tags
// all look up here so a term is defined identically everywhere.

export const GLOSSARY: Record<string, string> = {
  // ── Headline fundamentals (KPI labels match these keys exactly) ──────────────
  "Revenue": "Total sales the company booked in the period, before any costs are subtracted. The top line of the income statement.",
  "Gross Margin": "Gross profit (revenue minus the direct cost of goods sold) as a percent of revenue. Shows how profitable each dollar of sales is before overhead.",
  "Op. Margin": "Operating income as a percent of revenue — profit left after both cost of goods and operating expenses (R&D, SG&A), but before interest and taxes.",
  "Net Margin": "Net income as a percent of revenue — the share of every sales dollar that survives all costs, interest, and taxes as bottom-line profit.",
  "Diluted EPS": "Net income divided by all shares that would exist if options, warrants, and convertibles were exercised. The most conservative per-share profit figure.",
  "Cash": "Cash and short-term marketable securities on the balance sheet — the company's most liquid assets.",
  "Free Cash Flow": "Operating cash flow minus capital expenditures — the cash a business generates after funding its own operations and equipment.",
  "Operating Cash Flow": "Cash actually generated by core operations, stripping out accounting accruals. Harder to manipulate than reported net income.",
  "CapEx": "Capital expenditures — cash spent on property, plant, and equipment to maintain or grow the business.",
  "Long-Term Debt": "Borrowings due more than a year out. Rising leverage raises financial risk and interest costs.",
  "Net Income": "Bottom-line profit after every expense, interest payment, and tax. What ultimately accrues to shareholders.",

  // ── Growth conventions ───────────────────────────────────────────────────────
  "YoY": "Year-over-year — this period compared with the same period one year ago. Strips out seasonality.",
  "QoQ": "Quarter-over-quarter — this quarter compared with the immediately preceding quarter.",

  // ── SEC forms ──────────────────────────────────────────────────────────────
  "10-K": "Annual report: audited financial statements, risk factors, and a full business review. The most comprehensive filing.",
  "10-Q": "Quarterly report: unaudited financials and updates for one fiscal quarter.",
  "8-K": "Current report disclosing a material event (M&A, executive change, earnings, etc.) within ~4 business days of it happening.",
  "Form 4": "An insider's report of a personal trade in company stock, due within two business days of the transaction.",
  "13F-HR": "Quarterly disclosure of equity positions by institutional managers with over $100M under management. Filed up to 45 days after quarter-end, so it lags.",
  "SC 13D": "Filed when an investor crosses 5% ownership with intent to influence the company — the classic activist signal.",
  "SC 13G": "The passive-investor version of a 5%+ ownership disclosure: no intent to control management.",
  "Form 144": "An insider's notice of intent to sell restricted stock, filed before the sale executes.",
  "NT 10-K": "A 'Notification of Late Filing' — the company warns it will miss the deadline for a required report. Often an early distress signal.",

  // ── Concepts ─────────────────────────────────────────────────────────────────
  "10b5-1": "A pre-arranged trading plan that lets insiders schedule trades in advance, providing a defense against insider-trading claims. Trades under it are less informative than discretionary ones.",
  "Activist": "An investor who takes a large stake to push for change — board seats, spin-offs, buybacks, or a sale of the company.",
  "Guidance": "Management's own forecast for future revenue or earnings. A raise or cut often moves the stock more than the reported results themselves.",
  "Dilution": "An increase in share count (from new stock issuance) that shrinks each existing shareholder's slice of the company.",
  "Restatement": "A correction of previously reported financial statements — a serious red flag about accounting reliability.",
  "Insider": "An officer, director, or 10%+ owner whose trades must be reported. Cluster buying is a well-studied bullish signal.",
  "Institutional Holdings": "Positions held by large professional managers (funds, banks). Shows whether 'smart money' is accumulating or distributing.",
  "Beneficial Ownership": "Disclosure triggered when any investor crosses 5% ownership of a class of shares (Schedule 13D or 13G).",
  "Open-market buy": "A Form 4 transaction with code 'P' — an insider buying shares on the open market with their own cash. The most informative insider trade, unlike grants, option exercises, or tax-withholding sales.",
  "Cluster buying": "Several different insiders at the same company buying on the open market within a short window — one of the most reliable bullish insider signals, since it reflects shared conviction rather than one person's circumstances.",
  "EOD price": "End-of-day closing price from the public market feed. Updated daily after the close, not in realtime — a reference for returns and 52-week context, not a live quote.",
  "% off 52-wk high": "How far the latest close sits below the highest close of the trailing 52 weeks. Near 0% means the stock is at its one-year peak; a large negative means it has pulled back from it.",

  // ── Valuation ────────────────────────────────────────────────────────────────
  "Market Cap": "The total market value of a company's equity — latest share price times shares outstanding. Uses weighted-average diluted shares as a close proxy.",
  "P/E (TTM)": "Price-to-earnings: share price divided by trailing-twelve-month diluted EPS. A rough gauge of how many dollars investors pay per dollar of annual profit. Shown only when EPS is positive.",
  "P/S (TTM)": "Price-to-sales: market cap divided by trailing-twelve-month revenue. Useful for companies with thin or negative earnings where P/E breaks down.",

  // ── Technicals ─────────────────────────────────────────────────────────────────
  "Golden Cross": "When the 50-day moving average crosses above the 200-day — a widely-watched signal that a sustained uptrend may be starting.",
  "Death Cross": "When the 50-day moving average crosses below the 200-day — a widely-watched signal that a sustained downtrend may be starting.",
  "RSI": "Relative Strength Index (14-day): a 0–100 momentum gauge. Above 70 is often called 'overbought', below 30 'oversold'. A context clue, not a trade trigger.",
  "52-wk Breakout": "The latest close is a fresh 52-week high — price is at the top of its one-year range, a momentum signal.",
  "Volume Spike": "The latest session's share volume is well above its 30-day average — unusual trading interest that often accompanies news.",
};

/** Look up a definition by exact key. Returns undefined if not defined. */
export function defOf(key: string): string | undefined {
  return GLOSSARY[key];
}
